package at.jku.risc.uarau.data.term;

import java.util.Set;

/**
 * Implemented by:
 * <pre>
 * ├ {@linkplain GroundTerm}
 * │ └ {@linkplain MappedVariableTerm}
 * ├ {@linkplain FunctionTerm}
 * └ {@linkplain VariableTerm}
 * </pre>
 * GroundTerms and MappedVariableTerms can appear in the problem input.
 * <br>
 * FunctionTerms and VariableTerms are generated by the {@linkplain at.jku.risc.uarau.Algorithm Algorithm},
 * and appear in the {@linkplain at.jku.risc.uarau.data.Solution#generalization Solution.generalizations}
 * and their {@linkplain at.jku.risc.uarau.data.Witness Witnesses}.
 */
public interface Term {
    /**
     * The set of variables (excluding ANON) which appear as sub-terms in this term.
     */
    Set<Integer> v_named();
}
