package at.jku.risc.aau.term;

import at.jku.risc.aau.Solution;
import at.jku.risc.aau.Witness;
import at.jku.risc.aau.impl.Algorithm;

import java.util.Set;

/**
 * Implemented by:
 * <pre>
 * ├ {@linkplain GroundTerm}
 * │ └ {@linkplain MappedVariableTerm}
 * ├ {@linkplain FunctionTerm}
 * └ {@linkplain VariableTerm}
 * </pre>
 * GroundTerms and MappedVariableTerms can appear in the problem input.
 * <br>
 * FunctionTerms and VariableTerms are generated by the {@linkplain Algorithm Algorithm},
 * and appear in the {@linkplain Solution#generalization Solution.generalizations}
 * and their {@linkplain Witness Witnesses}.
 */
public interface Term {
    /**
     * The set of variables (excluding ANON) which appear as sub-terms in this term.
     */
    Set<Integer> namedVariables();
}
